package com.movierec.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "test")
@DynamoDBDocument
public class Movie {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String movieID;

    @DynamoDBAttribute(attributeName="budget")
    private String budget;

    @DynamoDBAttribute(attributeName="genres")
    private String genres;

    @DynamoDBAttribute(attributeName="homepage")
    private String homepage;

    @DynamoDBAttribute(attributeName="id")
    private String id;

    @DynamoDBAttribute(attributeName="keywords")
    private String keywords;

    @DynamoDBAttribute(attributeName="original_language")
    private String originalLanguage;

    @DynamoDBAttribute(attributeName="original_title")
    private String originalTitle;

    @DynamoDBAttribute(attributeName="overview")
    private String overview;

    @DynamoDBAttribute(attributeName="popularity")
    private String popularity;

    @DynamoDBAttribute(attributeName="production_companies")
    private String productionCompanies;

    @DynamoDBAttribute(attributeName="production_countries")
    private String productionCountries;

    @DynamoDBAttribute(attributeName="release_date")
    private String releaseDate;

    @DynamoDBAttribute(attributeName="revenue")
    private String revenue;

    @DynamoDBAttribute(attributeName="runtime")
    private String runtime;

    @DynamoDBAttribute(attributeName="spoken_languages")
    private String spokenLanguages;

    @DynamoDBAttribute(attributeName="status")
    private String status;

    @DynamoDBAttribute(attributeName="tagline")
    private String tagline;

    @DynamoDBAttribute(attributeName="title")
    private String title;

    @DynamoDBAttribute(attributeName="vote_average")
    private String voteAverage;

    @DynamoDBAttribute(attributeName="vote_count")
    private String voteCount;

}
